print("Olá,mundo")
print("fala ae carlão")
print("fala ae carlinhos")
print("e o frifas nada ainda")
print("apenas um cara traquilo que acorda cedo pra ir pra nurap")
print("apenas um cara tranquilo que quer ganhar dinheiro dormindo")
print("apenas um cara tranquilo que quer o decimo terceiro")
print("apenas um cara tranquilo")
print("apenas eu")
print("dor  mir é bom")
